# docker-compose.yml
version: '3.8'

services:
  service-hosts:
    image: service_hosts_py:latest
    container_name: service-hosts
    volumes:
      - volume_service_hosts_py:/app/data
    environment:
      - DB=/app/data/hosts.db
#    ports:
#      - "8001:8000"

  service-auth:
    image: service_auth_py:latest
    container_name: service-auth
    volumes:
      - volume_service_auth_py:/app/data
    environment:
      - DB=/app/data/auth.db
#    ports:
#      - "8002:8000"

  service-gateway:
    image: service_gateway_py:latest
    container_name: service-gateway
    environment:
      - HOSTS_URL=http://service-hosts:8000
      - AUTH_URL=http://service-auth:8000
      - SYNC_OUTLET_URL=http://localhost:8765 # If this refers to a service outside compose or on host
      - SYNC_MAIN_URL=http://localhost:8766   # If this refers to a service outside compose or on host
    ports:
      - "8000:8000"
    depends_on:
      - service-hosts # Ensure hosts and auth are up before gateway starts
      - service-auth

  web-client-dashboard:
    image: host-dashboard:latest
    container_name: web-client-dashboard
    ports:
      - "8080:8000"

volumes:
  volume_service_hosts_py:
    external: true
  volume_service_auth_py:
    external: true
